### ISSUE TITLE
mongo refuses to start up in --nodb mode

### ISSUE THREAD

**Issue by cswanson310** [justinjmoses/mongo-views#14]
$ ./mongo --nodb
MongoDB shell version: 3.1.0-pre-
mongo-views is initiating!
2015-03-11T12:20:29.187-0400 E QUERY    ReferenceError: db is not defined
    at getCurrentDb (/Users/charlie/github/my-mongo-views/lib/config.js:23:20)
    at loadViewsInDB (/Users/charlie/github/my-mongo-views/lib/init.js:94:13)
    at Object.init.js (/Users/charlie/github/my-mongo-views/lib/init.js:133:5)
    at DBCollection (/Users/charlie/.mongo-views.js:29:34)
    at /Users/charlie/.mongo-views.js:31:3
    at /Users/charlie/.mongorc.js:2:1 at /Users/charlie/github/my-mongo-views/lib/config.js:23
2015-03-11T12:20:29.187-0400 E QUERY    Error: error loading js file: /Users/charlie/.mongo-views.js
    at /Users/charlie/.mongorc.js:2:1 at /Users/charlie/.mongorc.js:2
The ".mongorc.js" file located in your home folder could not be executed

**Comment by imlucas** [comment]
@justinjmoses mind taking a look?

**Comment by jjgonecrypto** [comment]
@imlucas will do this weekend.

**Comment by GeertBosch** [comment]
Just ran into this today and was going to file a bug. Now I'll just add my "me too".

**Comment by aman-compro** [comment]
Ran into the same issue, but also found the solution. 

Please check the **.mongorc.js** file in your home directory and check if you have used the **db variable** in it.
